language: objective-c
install:
  - brew remove --force xctool
  - brew install xctool --HEAD

script:
   - xctool test -workspace kiwi-blocks-demo/kiwi-blocks-demo.xcworkspace -scheme kiwi-blocks-demo -sdk iphonesimulator8.1
